'use client';

import { useCallback, useEffect, useState } from 'react';
import { Loader2, MonitorPlay, Sparkles } from 'lucide-react';
import { authFetch } from '@/lib/auth';
import { cn } from '@/lib/utils';
import { useT, useLanguage, type Messages } from '@/lib/i18n';
import { ProjectorPlayer } from '@/components/dashboard/projector-player';
import { buildDemoHtml, DEMO_KEY } from './demo';

/* ------------------------------------------------------------------ */
/*  Types                                                              */
/* ------------------------------------------------------------------ */

interface ProjectorItem {
  name: string;
  path: string;
}

/* ------------------------------------------------------------------ */
/*  i18n                                                               */
/* ------------------------------------------------------------------ */

const messages = {
  en: {
    title: 'WkFlow Generation',
    subtitle: 'Ministry workflows and micro-tools generated by your agent',
    loadError: 'Failed to load workflows',
    emptyTitle: 'No workflows yet. Ask your agent to generate one for you!',
    viewDemo: 'View demo',
    demoCardTitle: 'How it works',
    demoCardHint: 'Interactive demo — see how an agent builds a skill',
    fallbackTitle: 'WkFlow Generation',
  },
  'zh-TW': {
    title: '工作流程生成',
    subtitle: '由您的代理生成的事工工作流程與微型工具',
    loadError: '無法載入工作流程',
    emptyTitle: '尚無工作流程。請您的代理為您生成一個！',
    viewDemo: '查看示範',
    demoCardTitle: '運作原理',
    demoCardHint: '互動示範 — 看看代理如何打造技能',
    fallbackTitle: '工作流程生成',
  },
} satisfies Messages<{
  title: string;
  subtitle: string;
  loadError: string;
  emptyTitle: string;
  viewDemo: string;
  demoCardTitle: string;
  demoCardHint: string;
  fallbackTitle: string;
}>;

/* ------------------------------------------------------------------ */
/*  Page                                                               */
/* ------------------------------------------------------------------ */

export default function ProjectorPage() {
  const t = useT(messages);
  const { lang } = useLanguage();
  const [items, setItems] = useState<ProjectorItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [activeItem, setActiveItem] = useState<string | null>(null);
  const [demoHtml, setDemoHtml] = useState<string | null>(null);

  const fetchItems = useCallback(async () => {
    try {
      const res = await authFetch<{ success: boolean; data: ProjectorItem[] }>(
        '/api/v1/workspace/projector',
      );
      setItems(Array.isArray(res.data) ? res.data : []);
    } catch {
      setError(t.loadError);
    } finally {
      setLoading(false);
    }
  }, [t]);

  useEffect(() => {
    void fetchItems();
  }, [fetchItems]);

  // The built-in demo renders entirely client-side — no API call. It teaches how
  // an agent + skills + memory build a Projector tool, and reuses the real
  // `projector:save` protocol to write a generated SKILL.md into the workspace.
  const openDemo = useCallback(() => {
    setActiveItem(DEMO_KEY);
    setDemoHtml(buildDemoHtml(lang));
  }, [lang]);

  const closeViewer = useCallback(() => {
    setActiveItem(null);
    setDemoHtml(null);
  }, []);

  const dialogTitle = activeItem === DEMO_KEY ? t.demoCardTitle : (activeItem ?? t.fallbackTitle);

  if (loading) {
    return (
      <div className="flex h-64 items-center justify-center">
        <Loader2 className="size-6 animate-spin text-muted-foreground" />
      </div>
    );
  }

  return (
    <div className="flex flex-col gap-6">
      {/* Header */}
      <div className="flex items-start justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold tracking-tight">{t.title}</h1>
          <p className="text-sm text-muted-foreground">{t.subtitle}</p>
        </div>
        <button
          onClick={openDemo}
          className="inline-flex shrink-0 items-center gap-2 rounded-lg border border-primary/40 bg-primary/10 px-3 py-2 text-sm font-medium text-primary transition-colors hover:bg-primary/20"
        >
          <Sparkles className="size-4" />
          {t.viewDemo}
        </button>
      </div>

      {/* Error */}
      {error && (
        <div className="rounded-md border border-destructive/50 bg-destructive/10 px-4 py-3 text-sm text-destructive">
          {error}
        </div>
      )}

      {/* Demo CTA card — always available so anyone can learn the workflow. */}
      <button
        onClick={openDemo}
        className="group flex items-center gap-4 rounded-lg border border-dashed border-primary/40 bg-card px-5 py-4 text-left transition-colors hover:bg-accent"
      >
        <div className="flex size-10 shrink-0 items-center justify-center rounded-lg bg-primary/15 text-primary">
          <Sparkles className="size-5" />
        </div>
        <div className="flex flex-col">
          <span className="text-sm font-semibold">{t.demoCardTitle}</span>
          <span className="text-xs text-muted-foreground">{t.demoCardHint}</span>
        </div>
      </button>

      {/* Empty state */}
      {items.length === 0 && !error && (
        <div className="flex flex-col items-center justify-center rounded-lg border border-dashed py-16 text-center">
          <MonitorPlay className="mb-3 size-10 text-muted-foreground" />
          <p className="text-sm text-muted-foreground">{t.emptyTitle}</p>
        </div>
      )}

      {/* Card grid */}
      {items.length > 0 && (
        <div className="grid grid-cols-2 gap-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5">
          {items.map((item) => (
            <button
              key={item.name}
              className={cn(
                'flex cursor-pointer items-center gap-2 rounded-lg border bg-card px-4 py-3 text-left text-sm font-medium transition-colors hover:bg-accent hover:text-accent-foreground',
                activeItem === item.name && 'ring-2 ring-primary bg-accent text-accent-foreground',
              )}
              onClick={() => setActiveItem(item.name)}
            >
              <MonitorPlay className="size-4 shrink-0 text-muted-foreground" />
              {item.name}
            </button>
          ))}
        </div>
      )}

      <ProjectorPlayer
        name={activeItem === DEMO_KEY ? null : activeItem}
        html={demoHtml}
        title={dialogTitle}
        onClose={closeViewer}
        onError={setError}
      />
    </div>
  );
}
